version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: 'kako'
      RABBITMQ_DEFAULT_PASS: 'kako123456'
    ports:
      - '5672:5672'
      - '15672:15672'
  postgre:
    container_name: 'postgres_ddd_base'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kako123456
      POSTGRES_USER: kako
      POSTGRES_DB: SolidBase
    ports:
      - '5432:5433'
    expose:
      - '5433'
  mysql:
    container_name: 'mysql_ddd_base'
    image: mysql-timezone:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'SolidBase'
      TZ: 'Europe/Sofia'
      MYSQL_USER: 'kako'
      MYSQL_PASSWORD: 'kako123456'
      MYSQL_ROOT_PASSWORD: 'kako123456'
    #command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+09:00']
    ports:
      - '3306:3306'
    expose:
      - '3306'
